### ISSUE TITLE
Behaviour of convert.py script when updating already existing basis file.

### ISSUE THREAD

**Issue by MJKirk** [wcxf/wcxf-bases#11]
The convert.py script only checks if there is already a corresponding JSON / YAML file, not if they contain the same information.
So if you add operators to an already existing basis, then run the convert script, the changes don't get propogated.

Not huge issue since it's pretty obvious to pick up on in a PR, but I guess ideally there'd be some form of checking the operators in each one to see which is the more/less complete and therefore which form needs regenerating.

**Comment by DavidMStraub** [comment]
I'm not sure it's worth reading the existing files and comparing everything. Seems more like a documentation/logging issue to make users aware that they should delete existing files if they want to regenerate the JSONs?

**Comment by MJKirk** [comment]
Closed by #12
